version: "2"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  lasp-client:
    environment:
      - TAG=client
      - REDIS_SERVICE_HOST=redis
      - REDIS_PORT=6379
      - LASP_BRANCH=master
      - DOCKER_COMPOSE=true
    build: .
  lasp-server:
    environment:
      - TAG=server
      - REDIS_SERVICE_HOST=redis
      - REDIS_PORT=6379
      - LASP_BRANCH=master
      - DOCKER_COMPOSE=true
    build: .
