{application,gen_flow,
             [{description,"Generic abstraction for building dataflow computations."},
              {vsn,"0.0.5"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {modules,[gen_flow,gen_flow_example]},
              {env,[]},
              {maintainers,["Chris Meiklejohn","Borja o'Cook"]},
              {licenses,["Apache 2.0"]},
              {links,[{"Github","https://github.com/lasp-lang/gen_flow"}]}]}.
